[fortuneo] Add condition to prevent get_currency() AttributeError crash
Some fortuneo connections randomly crash because the balance is not
fetched correctly and the "account.get_currency(balance)" returns:
AttributeError: 'NoneType' object has no attribute 'upper'
The "elif balance" makes sure that there is a balance before trying to
extract a currency from a NoneType.

Closes: 16284@sibi