[ing] Added condition to get_isin() method
Some ING connections are crashing because we try to get an element of an
empty xpath:
self.doc.xpath('//div[@id="headFiche"]//span[@id="test3"]/text()')[0].split(' - ')[0].strip()
IndexError: list index out of range
I added an "if isin" condition to rpevent the recurrent bugs also they
are not always reproducible locally.

Closes: 12520@sibi