[s2e] Removed CleanText to avoid crash when Dict is null
Some JSON details have values equal to 'null' in the JSON and CleanText
crashes with "AttributeError: 'NoneType' object has no attribute 'itertext'".
There is no need for CleanText here, as most JSON values, the strings
are already clean.